
# AnyTextEditor - Free Online Text Editor © 2022 AnyTextEditor
# Edit your texts for free online, improve them and create new ones

# https://anytexteditor.com

set nm1 to array [ "A" "Ara" "Alfo" "Bari" "Be" "Bo" "Bha" "Bu" "Ba" "Bra" "Bro" "Brou" "Bru" "Da" "Dalo" "Dare" "De" "Dhu" "Dho" "Do" "Dora" "Dwo" "Dou" "Duri" "Du" "El" "Eri" "Fi" "Fo" "Fo" "Ga" "Gi" "Gla" "Glori" "Go" "Gra" "Gro" "Groo" "Gru" "Grou" "Ha" "Ha" "He" "He" "Ho" "Hou" "Hu" "Ja" "Jo" "Ka" "Khe" "Khu" "Khou" "Ko" "Ku" "Ki" "Kra" "Kro" "Lo" "Lu" "Lo" "Ma" "Mo" "Mu" "Na" "No" "Nu" "Nora" "Nura" "Ne" "No" "O" "Ori" "Rei" "Ra" "Ru" "Sa" "Si" "Sna" "Sko" "Ska" "Stro" "The" "Thi" "Tho" "Thra" "Tha" "Tore" "Tha" "Thra" "Thro" "Thu" "Tu" "U" "Umi" "Va" "Vo" "Whu" "We" "Wera" "Yu" "Yo" "Ya" ]
set nm2 to array [ "b" "br" "dd" "d" "dr" "dm" "dgr" "f" "fr" "gr" "gg" "gh" "gn" "k" "kh" "kgr" "kdr" "kk" "kh" "kr" "l" "lg" "lgr" "ldr" "lm" "md" "mn" "m" *"mm" "mr" "n" "nd" "ndr" "ngr" "nm" "r" "rr" "rgr" "rdr" "rb" "rg" "rn" "rh" "rd" "rm" "rs" "rf" "s" "ss" "sdr" "sgr" "st" "str" "t" "tr" "tm" "th" "tdr" "tgr" "v" "vr" *"z" "zm" "zn" "zz" ]
set nm3 to array [ "ac" "aic" "aec" "ec" "eac" "ic" "oc" "oic" "ouc" "ack" "aeck" "eck" "eack" "ick" "ock" "oick" "ouck" "uck" "uc" "ad" "aed" "ed" "ead" "id" "od" "oid" "oud" "ud" "uid" "ag" "aeg" "eg" "eag" "ig" "og" "oug" "ug" "ak" "aek" "ek" "eak" "ik" "ok" "oki" "uk" "uik" "ouk" "uki" "al" "ael" "el" "eal" "il" "ol" "oli" "olin" "olim" "olir" "oul" "ul" "uli" "ulim" "ulir" "uil" "am" "ami" "amli" "amri" "aem" "em" "eam" "im" "om" "omli" "omri" "omi" "oum" "um" "umi" "umir" "umin" "umli" "umlir" "umlin" "umri" "an" "aen" "en" "ean" "in" "on" "onlim" "onlir" "oun" "un" "unli" "unri" "ar" "arlum" "arlun" "arlug" "arlig" "aer" "er" "erlum" "erlun" "erlug" "erlig" "ear" "ir" "irlum" "irlun" "or" "orli" "orlim" "orlum" "orlun" "orlig" "orlug" "oir" "our" "ur" "uri" "urim" "urum" "us" "as" "ous" "aes" "eas" "at" "atir" "atum" "atin" "aet" "et" "eat" "it" "ot" "otir" "atin" "otum" "out" "ut" "ath" "aeth" "eth" "eath" "ith" "oth" "outh" "uth" ]
set nm7 to array [ "Ale" "Amber" "Anvil" "Ash" "Axe" "Barbed" "Barrel" "Battle" "Beast" "Bone" "Beryl" "Bitter" "Black" "Blazing" "Blessed" "Blood" "Blunt" "Bone" "Bottle" "Boulder" "Brew" "Brick" "Bright" "Bristle" "Broad" "Bronze" "Brown" "Cave" "Cask" "Chain" "Crag" "Chaos" "Coal" "Coin" "Copper" "Dark" "Deep" "Dim" "Dragon" "Drake" "Dusk" "Earth" "Ember" "Fiery" "Flint" "Flask" "Flint" "Flat" "Forge" "Frost" "Giant" "Gold" "Golden" "Granite" "Gravel" "Gray" "Great" "Grey" "Grim" "Grumble" "Hammer" "Hard" "Heavy" "Hill" "Honor" "Horn" "Ice" "Ingot" "Iron" "Jade" "Keg" "Kobold" "Krag" "Lead" "Large" "Lava" "Leather" "Light" "Long" "Marble" "Magma" "Merry" "Metal" "Mithril" "Mine" "Mountain" "Mud" "Night" "Noble" "Oak" "Oaken" "Onyx" "Opal" "Ore" "Orc" "Plate" "Pebble" "Red" "Rune" "Ruby" "Sapphire" "Shadow" "Shatter" "Smelt" "Silver" "Snow" "Steel" "Storm" "Strong" "Troll" "Thunder" "Twilight" "Treasure" "Under" "War" "Warm" "Whit" "Wind" "Wold" "Wraith" "Wyvern" ]
set nm8 to array [ "arm" "armour" "axe" "back" "bane" "beard" "basher" "belly" "belt" "bender" "blade" "born" "bow" "braid" "braids" "branch" "brand" "breaker" "brew" "brewer" "bringer" "brow" "buckle" "buster" "chest" "chin" "cloak" "coat" "delver" "digger" "foot" "fall" "fury" "finger" "flayer" "feet" "forge" "forged" "grog" "grip" "guard" "gut" "granite" "hand" "head" "heart" "helm" "hide" "hood" "horn" "jaw" "mace" "mail" "maker" "mantle" "mane" "master" "maul" "miner" "pike" "rock" "river" "shield" "shaper" "sword" "shoulder" "stone" "spine" "sunder" "thane" "toe" "tank" "view" ]
join [ random &nm1 random &nm2 random &nm3 " " random &nm7 random &nm8 ] by pass